### ISSUE TITLE
microbit module

### ISSUE THREAD

**Issue by jheller** [musabkilic/MicroBike#4]
I think I'm missing something really obvious here, so apologies for raising an issue like this.

I have the micro:bit connected to my macbook, and have installed the bitio library on it. I cloned this repo and installed the pyuserinput module requirement.

But I can't run controller.py on my mac because it fails at the first line. I have no microbit module, and I can't find anywhere how to install it on my mac. What am I missing?

**Comment by musabkilic** [comment]
Hello,

I'm sorry to hear that, there is no need to apologize. To make the further set-ups easier, I've came up with this solution. Let me know if it works for you, because I'm planning to create a pull request to bitio.

Clone [my fork of bitio](https://github.com/musabkilic/bitio). Then open a terminal and run the following: `pip install -U ./bitio/src/`. You should have the microbit module now. Try running controller.py to see if it works. Let me know if you have any problems.

Kind regards,
Musab

**Comment by jheller** [comment]
Hi Musab,

Thanks for the prompt reply. I understand now. If I had read the README on the bitio repo properly I would have found the answer myself. :-)

Is the a reason to use your fork rather than the original? Is there something you have added?

**Comment by musabkilic** [comment]
Hi,

Yes, I've added [this file](https://github.com/musabkilic/bitio/blob/master/src/setup.py) which is a standard setup.py file that tells pip how to install properly; otherwise pip install command doesn't work. [More info on official Python docs](https://docs.python.org/3.7/distutils/setupscript.html).

I love getting comments from people that use my code, so let me know about your opinions when/if you play any games with MicroBike :).

Regards,
-M
