### ISSUE TITLE
i  got the following "error"

### ISSUE THREAD

**Issue by jazzhar** [musabkilic/MicroBike#5]
Could not find a version that satisfies the requirement pyHook (from pyuserinput->-r requirements.txt (line 1)) (from versions: )
No matching distribution found for pyHook (from pyuserinput->-r requirements.txt (line 1))

how di i fix this?

**Comment by musabkilic** [comment]
Hello! Which version of Python do you have installed?

**Comment by jazzhar** [comment]
thank you for the quick response!. i have the latest version installed.

Op ma 20 apr. 2020 om 13:22 schreef Musab Kılıç <notifications@github.com>:

**Comment by musabkilic** [comment]
Is it Python 3.8.2? If you are not sure, you can open a command line and type "python --version" to see which version is installed.

**Comment by jazzhar** [comment]
hmm strange on my start menu (windows 10) it says python 3.8. using cmd it says: Python 3.6.3

**Comment by jazzhar** [comment]
when i open python from start it does say 3.8.2

**Comment by musabkilic** [comment]
I think you have two versions of it installed. Can you also run "pip --version" on command line to see which version do pip install modules to? The output will be in the form of "pip {PIP_VERSION} from {PATH} (python {PYTHON_VERSION})" Python version is what you are looking for.

**Comment by jazzhar** [comment]
this is what it send me back: pip 20.0.2 from c:\users\{MYUSERANME}\appdata\local\programs\python\python36\lib\site-packages\pip (python 3.6)

**Comment by musabkilic** [comment]
Okay, this is what I think is happening: pyHook is kind of an old module, so they might not be an official version released for Python 3.6. But there is another way, ["Unofficial Windows Binaries for Python Extension Packages" by Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/) is generally the go-to binaries to install if there are non official available. You can find the ones for pyHook on [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook).

To install, download the file according to your computer(32-bit or 64-bit) for Python 3.6(because this is the one that runs when you run "python" from command line). And open up a command line prompt on your download folder. Type "pip install pyHook‑1.5.1‑cp36‑cp36m‑win{_amd64/32}.whl"(change what is in {} according to your own). It should install pyHook, and you can continue the installing process where you left off(you need to run "pip install -r requirements.txt" again).

**Comment by jazzhar** [comment]
i got alomst everything working. when i do everything my microbit is showing a flashing arrow pointing to left. when i press a or b its just showing a line

**Comment by musabkilic** [comment]
The program waits and flashes an arrow pointed left to say you need to press a button. After you press, it shows an arrow if you tilt it, otherwise if its staying straight it just shows a line. Try moving, tilting, rotating the microbit till you see an arrow pointed at the way you rotate it.

**Comment by musabkilic** [comment]
I updated the code, and switched to Pynput from PyUserInput for future installations. Pynput doesn't depend on PyHook and is an updated module so there should be less problems installing it I hope. If you can't make it work with PyUserInput, delete MicroBike folder and clone it again to get the updated code.
