### ISSUE TITLE
i installed pyuserinput and bitio and mbed-os in the same file and 

### ISSUE THREAD

**Issue by hekhek123** [musabkilic/MicroBike#7]
i installed pyuserinput and bitio and mbed-os in the same file and i did put controller.py in bitio/src/, but when i run it controller.py, it said running ur program in the end. it still doesnt work. i am looking for some help. i am student, and this assignment is due soon.

**Comment by musabkilic** [comment]
Hi! Can you give more details on the output you are getting? A screenshot might be helpful too. The updated code uses Pynput, not pyuserinput which might be related to your issue.

Would you mind me asking about this assignment you are talking about and where you study? MicroBike has been used for education purposes in the past but I didn't know it was still used in classrooms, that's why I'm asking.

**Comment by hekhek123** [comment]
OMG i didn't expect u responded it so quickly! thanks! i am a monash IT major student. well monash didn't ask us to use microbike, but i am interested on it, this assignment is about using microbit to make something fun. i am trying to use pynput to fix and getting some screenshots maybe.

**Comment by hekhek123** [comment]
i mean my python file path is like C:\Users\hek\.....\....\.., but my i installed microbike, bitio and mbed-os(3 folders) in C:\Users\hek(file path). does that matter? and i did installed pynput and bitio by using pip installing command. after detecting my microbit, microbit shows an arrow points to left, and i pressed A button, then it became a line which is 5 dots. that is pretty much it, no matter how hard i swing it, it didnt change at all

**Comment by hekhek123** [comment]
![image](https://user-images.githubusercontent.com/74418994/99093507-aabc1e00-2626-11eb-8ab2-b3bb4fe6bc0e.png)

**Comment by musabkilic** [comment]
No problem! I'm glad that you chose MicroBike for your assignment :). I believe the code works as intended, it waits for you to press A and shows you the current direction. A straight line means that you hold the micro:bit steady, try tilting it towards you(like you are driving a real motorcycle), and try steering it. You should see arrows pointing at the direction you are steering:
![](https://raw.githubusercontent.com/musabkilic/MicroBike/master/res/microbike.gif)

At this point the program started simulating key presses, try to find a motorcycle game online and you can play it using your micro:bit. Make sure the game uses arrow keys otherwise the code won't work unless you make modifications.

**Comment by hekhek123** [comment]
well.it still does not work, no matter how hard i swing it and tilt it after it shows a line.is this because the locations of  microbike, bitio and mbed-os  are wrong?i just use git clone to install them in C:\Users\hek.  did i miss some steps?

**Comment by hekhek123** [comment]
is it because i am using python3.8? and i did not install mbed-os correctly?

**Comment by hekhek123** [comment]
![image](https://user-images.githubusercontent.com/74418994/99137477-306bb800-267f-11eb-8189-cb5ec336736d.png)
i am having a new problem

**Comment by hekhek123** [comment]
omg bro i did it!!! thanks  a lot!!

**Comment by hekhek123** [comment]
NEWSFLASH - using with a V1.5 micro:bit
If you have a V1.5 micro:bit, a new sensor was fitted for the accelerometer and compass. This requires new hardware drivers in order to work.

A very quick fix for this is to drag the bitio.hex file inside this repository into https://python.microbit.org then press the DOWNLOAD button. This will update the internal drivers automaticaly and allow the accelerometer to work on both older and newer devices. (I will update this repo soon, when testing has been completed)


thats how i did it!! thanks

**Comment by musabkilic** [comment]
🎉
